# Generated by Django 4.0.4 on 2022-07-28 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depId', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1)),
                ('docId', models.IntegerField(primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=40)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('age', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Nacimiento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('personal_files', models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('genre', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1)),
                ('patId', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('numId', models.IntegerField(primary_key=True, serialize=False)),
                ('histo', models.CharField(max_length=360)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.patient')),
            ],
        ),
    ]
