# Generated by Django 3.2.14 on 2022-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depId', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='Otro', max_length=1)),
                ('docId', models.IntegerField(primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('specialization', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='Otro', max_length=1)),
                ('patId', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
