# Generated by Django 3.2.14 on 2022-08-01 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('tel', models.IntegerField(verbose_name='Teléfono')),
                ('head_of', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=60, verbose_name='Apellido')),
                ('genre', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1, verbose_name='Género')),
                ('DNI', models.IntegerField(unique=True, verbose_name='DNI')),
                ('license', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('tel', models.IntegerField(verbose_name='Telefono')),
                ('address', models.CharField(max_length=60, verbose_name='Dirección')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.department', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=60, verbose_name='Apellido')),
                ('genre', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='O', max_length=1, verbose_name='Género')),
                ('DNI', models.IntegerField(unique=True, verbose_name='DNI')),
                ('register_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d', verbose_name='Imágen de Perfil')),
                ('personal_files', models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d', verbose_name='Archivos')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('tel', models.IntegerField(verbose_name='Telefono')),
                ('address', models.CharField(max_length=60, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(max_length=360)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.patient')),
            ],
        ),
    ]
