# Generated by Django 3.2.14 on 2022-07-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depId', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('head', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=60)),
                ('IdNumber', models.IntegerField()),
                ('license', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('speciality', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('IdNumber', models.CharField(max_length=20, unique=True)),
                ('birthDate', models.DateField()),
                ('genre', models.CharField(max_length=60)),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('medicalRecords', models.TextField(blank=True, default='None')),
                ('allergies', models.TextField(blank=True, default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeIn', models.TimeField(null=True)),
                ('timeOut', models.TimeField(null=True)),
                ('diagnose', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.doctor')),
                ('history', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.history')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.patient')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('appointmentDate', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('state', models.BooleanField()),
                ('cause', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.patient')),
            ],
        ),
    ]
